namespace: myapp

postgres:
  image: postgres:15
  db: mydb
  user: cG9zdGdyZXM= # base64 encoded
  password: YWRtaW4xMjM= # base64 encoded
  port: 5432
  replicas: 1

backend:
  image: backend-app:latest
  port: 5000
  replicas: 2

frontend:
  image: frontend-app:latest
  port: 80
  replicas: 2
  backend_app: backend
  nodePort: 30000
