apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | b64dec }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64dec }}
